### ISSUE TITLE
Bug in function `upload_prediction`

### ISSUE THREAD

**Issue by eduardocorrearaujo** [Mosqlimate-project/mosqlimate-client#20]
@luabida, could you help me?

In the help of the `upload_prediction` function says: 

<img width="1117" alt="Captura de Tela 2024-06-18 às 21 41 37" src="https://github.com/Mosqlimate-project/mosqlimate-client/assets/65051489/4a326a91-829e-4944-b1a4-93f88480450d">

but when I pass a dataframe as prediction I receive the error: 
`TypeError: Object of type DataFrame is not JSON serializable`

**Comment by eduardocorrearaujo** [comment]
The dataframe used is defined as (I passed it as dict here to be able to share the dataframe used): 

```
df_dict = {'dates': {0: datetime.date(2024, 1, 7),
  1: datetime.date(2024, 1, 14),
  2: datetime.date(2024, 1, 21),
  3: datetime.date(2024, 1, 28)},
 'preds': {0: 8505.734350266162,
  1: 9174.584527379222,
  2: 10833.945041681956,
  3: 12541.700235036375},
 'lower': {0: 4329.1522078491635,
  1: 3559.332898757307,
  2: 3283.5166748218526,
  3: 2897.6508459018632},
 'upper': {0: 18542.231490056503,
  1: 29417.27934448197,
  2: 51769.6202471171,
  3: 99248.14610693364},
 'adm_1': {0: 'PR', 1: 'PR', 2: 'PR', 3: 'PR'},
 'adm_0': {0: 'BR', 1: 'BR', 2: 'BR', 3: 'BR'},
 'adm_2': {0: None, 1: None, 2: None, 3: None}}

df = pd.DataFrame(df_dict)

**Comment by eduardocorrearaujo** [comment]
@fccoelho I also noticed that the prediction dataframe requires the columns `adm_2` (city-level), `adm_1` (state level), and `adm_0` (country level). Since the predictions will be made at the state level in the sprint, what do you think is better: filling `adm_2 = None` when predicting a state or changing the validation to just request one of the columns according to the adm_level registered when the model is saved on the platform?

**Comment by fccoelho** [comment]
The function signature is wrong. the prediction should be a JSON object IIRC.

**Comment by fccoelho** [comment]
> @fccoelho I also noticed that the prediction dataframe requires the columns `adm_2` (city-level), `adm_1` (state level), and `adm_0` (country level). Since the predictions will be made at the state level in the sprint, what do you think is better: filling `adm_2 = None` when predicting a state or changing the validation to just request one of the columns according to the adm_level registered when the model is saved on the platform?

Having the validation check just the column declared in the model record, is the Ideal solution. The second-best solution would be to fill the other columns with `pd.NA`

**Comment by eduardocorrearaujo** [comment]
> The function signature is wrong. the prediction should be a JSON object IIRC.

Yes, but in my understanding @luabida created the function in order to transform the prediction dataframe in a json internally.

**Comment by eduardocorrearaujo** [comment]
> > @fccoelho I also noticed that the prediction dataframe requires the columns `adm_2` (city-level), `adm_1` (state level), and `adm_0` (country level). Since the predictions will be made at the state level in the sprint, what do you think is better: filling `adm_2 = None` when predicting a state or changing the validation to just request one of the columns according to the adm_level registered when the model is saved on the platform?
> 
> Having the validation check just the column declared in the model record, is the Ideal solution. The second-best solution would be to fill the other columns with `pd.NA`

@luabida  Is it feasible to implement this check? Or should we keep the second-best solution?

**Comment by fccoelho** [comment]
> > The function signature is wrong. the prediction should be a JSON object IIRC.
> 
> Yes, but in my understanding @luabida created the function in order to transform the prediction dataframe in a json internally in the function.

Yes, but as you can see [here](https://github.com/Mosqlimate-project/mosqlimate-client/blob/cc3906b35f3124b67d8afdd70de3fa1bb4422fd9/mosqlient/registry/predictions.py#L93), it is not being converted.

**Comment by luabida** [comment]
> Also, when the function returns an error in POST, it just shows the number associated
We need to improve the error handling [here](https://github.com/Mosqlimate-project/Data-platform/blob/main/src/registry/validations.py#L56) and return the proper message with the status code, there's also the adm_level fix to be done in this validation (accept None in two of the adm columns)

**Comment by eduardocorrearaujo** [comment]
The `upload_prediction` does not allow sending a prediction with just the adm_level associated with the model. The other columns must be filled even if they are NULL. The validation must be improved in order to allow the user to provide a prediction with a single adm column.
