### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by fccoelho** [Mosqlimate-project/mosqlimate-client#3]
The client library must include three initial functionalities:

- [ ] Registering models 
- [ ] Uploading predictions
- [ ] Benchmarking predictions

The model registration and prediction uploading should be done programatically like the example below:
```python
from mosqlient.models import TemporalModel, SpatialModel

M = TemporalModel(id=xxxx) # pass model id in case the model is already registered in the platform
M.add_prediction(data) # data is the JSON object with the prediction. JSON is check for validity
M.sync() # upload predictions
```

The benchmarking should be done with the cli app

```bash
mosqbench -b <baseline_model_id> *.json
```
The command above should return the Skill scores of the predictions against the baseline model.

**Comment by eduardocorrearaujo** [comment]
Add:
- [ ] Download of data from API

**Comment by fccoelho** [comment]
The package needs to add some high level functions to help the user to interact with the platform, such as :

- `mosqlient. list_models(author_id, tag)` : list all models registered in the platform, with the possibility to filter by tag, or author id
- `mosqlient.list_tags()`: list all tags registered in the platforms
- `mosqlient.list_model_predictions(model_id)`: List all predictions generated by a model
- etc.

The library should make it possible to do everything you can do through the web interface, for example search for all predictions for a given location and period, download charts, etc.
